import Schedule_Appointment_page_title from '@salesforce/label/c.Schedule_Appointment_page_title';
import FollowUpAppointments_select_new_date_to_schedule from '@salesforce/label/c.FollowUpAppointments_select_new_date_to_schedule';
import FollowUpAppointments_select_an_available_appointment_time from '@salesforce/label/c.FollowUpAppointments_select_an_available_appointment_time';
import FollowUpAppointments_accept_new_appointment_button from '@salesforce/label/c.FollowUpAppointments_accept_new_appointment_button';
import FollowUpAppointments_next_button_title from '@salesforce/label/c.FollowUpAppointments_next_button_title';
import FollowUpAppointments_new_appointment_msg from '@salesforce/label/c.FollowUpAppointments_new_appointment_msg';
import FollowUpAppointments_same_appointment_selected_warning from '@salesforce/label/c.FollowUpAppointments_same_appointment_selected_warning';
import FollowUpAppointments_confirmation_service_requested from '@salesforce/label/c.FollowUpAppointments_confirmation_service_requested';
import FollowUpAppointments_selected_appointment_msg from '@salesforce/label/c.FollowUpAppointments_selected_appointment_msg';
import FollowUpAppointments_toastMessage_appointment_schedule from '@salesforce/label/c.FollowUpAppointments_toastMessage_appointment_schedule';
import FollowUpAppointments_confirmation_failure_message from '@salesforce/label/c.FollowUpAppointments_confirmation_failure_message';
import FollowUpAppointments_toastMessage_schedule_appointment_fail_message from '@salesforce/label/c.FollowUpAppointments_toastMessage_schedule_appointment_fail_message';
import FollowUpAppointments_assigned_to_you from '@salesforce/label/c.FollowUpAppointments_assigned_to_you';
import FollowUpAppointments_assigned_to_any_available_worker from '@salesforce/label/c.FollowUpAppointments_assigned_to_any_available_worker';

const customLabels = {
  FollowUpAppointments_select_new_date_to_schedule,
  FollowUpAppointments_select_an_available_appointment_time,
  FollowUpAppointments_accept_new_appointment_button,
  FollowUpAppointments_next_button_title,
  FollowUpAppointments_new_appointment_msg,
  FollowUpAppointments_same_appointment_selected_warning,
  FollowUpAppointments_confirmation_service_requested,
  FollowUpAppointments_selected_appointment_msg,
  Schedule_Appointment_page_title,
  FollowUpAppointments_toastMessage_appointment_schedule,
  FollowUpAppointments_confirmation_failure_message,
  FollowUpAppointments_toastMessage_schedule_appointment_fail_message,
  FollowUpAppointments_assigned_to_you,
  FollowUpAppointments_assigned_to_any_available_worker,
};

export default customLabels;
