import Reschedule_Appointment_MonthName_January from "@salesforce/label/c.Reschedule_Appointment_MonthName_January";
import Reschedule_Appointment_MonthName_February from "@salesforce/label/c.Reschedule_Appointment_MonthName_February";
import Reschedule_Appointment_MonthName_March from "@salesforce/label/c.Reschedule_Appointment_MonthName_March";
import Reschedule_Appointment_MonthName_April from "@salesforce/label/c.Reschedule_Appointment_MonthName_April";
import Reschedule_Appointment_MonthName_May from "@salesforce/label/c.Reschedule_Appointment_MonthName_May";
import Reschedule_Appointment_MonthName_June from "@salesforce/label/c.Reschedule_Appointment_MonthName_June";
import Reschedule_Appointment_MonthName_July from "@salesforce/label/c.Reschedule_Appointment_MonthName_July";
import Reschedule_Appointment_MonthName_August from "@salesforce/label/c.Reschedule_Appointment_MonthName_August";
import Reschedule_Appointment_MonthName_September from "@salesforce/label/c.Reschedule_Appointment_MonthName_September";
import Reschedule_Appointment_MonthName_October from "@salesforce/label/c.Reschedule_Appointment_MonthName_October";
import Reschedule_Appointment_MonthName_November from "@salesforce/label/c.Reschedule_Appointment_MonthName_November";
import Reschedule_Appointment_MonthName_December from "@salesforce/label/c.Reschedule_Appointment_MonthName_December";

import Reschedule_Appointment_WeekDayShort_Mon from "@salesforce/label/c.Reschedule_Appointment_WeekDayShort_Mon";
import Reschedule_Appointment_WeekDayShort_Tue from "@salesforce/label/c.Reschedule_Appointment_WeekDayShort_Tue";
import Reschedule_Appointment_WeekDayShort_Wed from "@salesforce/label/c.Reschedule_Appointment_WeekDayShort_Wed";
import Reschedule_Appointment_WeekDayShort_Thu from "@salesforce/label/c.Reschedule_Appointment_WeekDayShort_Thu";
import Reschedule_Appointment_WeekDayShort_Fri from "@salesforce/label/c.Reschedule_Appointment_WeekDayShort_Fri";
import Reschedule_Appointment_WeekDayShort_Saturday from "@salesforce/label/c.Reschedule_Appointment_WeekDayShort_Saturday";
import Reschedule_Appointment_WeekDayShort_Sunday from "@salesforce/label/c.Reschedule_Appointment_WeekDayShort_Sunday";
import Reschedule_Appointment_Select_a_Date from "@salesforce/label/c.Reschedule_Appointment_Select_a_Date";
import Reschedule_Appointment_OK from "@salesforce/label/c.Reschedule_Appointment_OK";

const customLabels = {
  Reschedule_Appointment_MonthName_January,
  Reschedule_Appointment_MonthName_February,
  Reschedule_Appointment_MonthName_March,
  Reschedule_Appointment_MonthName_April,
  Reschedule_Appointment_MonthName_May,
  Reschedule_Appointment_MonthName_June,
  Reschedule_Appointment_MonthName_July,
  Reschedule_Appointment_MonthName_August,
  Reschedule_Appointment_MonthName_September,
  Reschedule_Appointment_MonthName_October,
  Reschedule_Appointment_MonthName_November,
  Reschedule_Appointment_MonthName_December,

  Reschedule_Appointment_WeekDayShort_Mon,
  Reschedule_Appointment_WeekDayShort_Tue,
  Reschedule_Appointment_WeekDayShort_Wed,
  Reschedule_Appointment_WeekDayShort_Thu,
  Reschedule_Appointment_WeekDayShort_Fri,
  Reschedule_Appointment_WeekDayShort_Saturday,
  Reschedule_Appointment_WeekDayShort_Sunday,
  Reschedule_Appointment_Select_a_Date,
  Reschedule_Appointment_OK
};

export default customLabels;
