import FollowUpAppointments_add_step_button_label from '@salesforce/label/c.FollowUpAppointments_add_step_button_label';
import FollowUpAppointments_edit_step_text_label from '@salesforce/label/c.FollowUpAppointments_edit_step_text_label';
import FollowUpAppointments_new_step_text_label from '@salesforce/label/c.FollowUpAppointments_new_step_text_label';
import FollowUpAppointments_step_name_text from '@salesforce/label/c.FollowUpAppointments_step_name_text';
import FollowUpAppointments_Object_text from '@salesforce/label/c.FollowUpAppointments_Object_text';
import FollowUpAppointments_placeholder_step_name from '@salesforce/label/c.FollowUpAppointments_placeholder_step_name';
import FollowUpAppointments_select_fields from '@salesforce/label/c.FollowUpAppointments_select_fields';
import FollowUpAppointments_button_save from '@salesforce/label/c.FollowUpAppointments_button_save';
import FollowUpAppointments_button_cancel from '@salesforce/label/c.FollowUpAppointments_button_cancel';
import FollowUpAppointments_duallist_available_fields from '@salesforce/label/c.FollowUpAppointments_duallist_available_fields';
import FollowUpAppointments_duallist_selected_fields from '@salesforce/label/c.FollowUpAppointments_duallist_selected_fields';
import FollowUpAppointments_placeHolder_select_an_option from '@salesforce/label/c.FollowUpAppointments_placeHolder_select_an_option';
import FollowUpAppointments_placeholder_search_fields from '@salesforce/label/c.FollowUpAppointments_placeholder_search_fields';

import FollowUpAppointments_MobileWorkFlow_Info_text from '@salesforce/label/c.FollowUpAppointments_MobileWorkFlow_Info_text';
import FollowUpAppointments_MobileWorkFlow_info_help_url from '@salesforce/label/c.FollowUpAppointments_MobileWorkFlow_info_help_url';

import FollowUpAppointments_delete_step_heading from '@salesforce/label/c.FollowUpAppointments_delete_step_heading';
import FollowUpAppointments_delete_step_body from '@salesforce/label/c.FollowUpAppointments_delete_step_body';

import FollowUpAppointments_delete_cancel_button from '@salesforce/label/c.FollowUpAppointments_delete_cancel_button';
import FollowUpAppointments_delete_button_title from '@salesforce/label/c.FollowUpAppointments_delete_button_title';

import FollowUpAppointments_settings_duplicateScreenToastMessage from '@salesforce/label/c.FollowUpAppointments_settings_duplicateScreenToastMessage';
import FollowUpAppointments_settings_deleteScreenToastMessage from '@salesforce/label/c.FollowUpAppointments_settings_deleteScreenToastMessage';
import FollowUpAppointments_settings_createScreenToastMessage from '@salesforce/label/c.FollowUpAppointments_settings_createScreenToastMessage';

import FollowUpAppointments_settingPage_error_duplicate_screen from '@salesforce/label/c.FollowUpAppointments_settingPage_error_duplicate_screen';
import FollowUpAppointments_settingPage_error_delete_screen from '@salesforce/label/c.FollowUpAppointments_settingPage_error_delete_screen';
import FollowUpAppointments_workflow_addStepFailureMessage from '@salesforce/label/c.FollowUpAppointments_workflow_addStepFailureMessage';
import FollowUpAppointments_settingPage_save_message from '@salesforce/label/c.FollowUpAppointments_settingPage_save_message';
import FollowUpAppointments_settingPage_error_message from '@salesforce/label/c.FollowUpAppointments_settingPage_error_message';

const customLabels = {
  FollowUpAppointments_add_step_button_label,
  FollowUpAppointments_edit_step_text_label,
  FollowUpAppointments_new_step_text_label,
  FollowUpAppointments_step_name_text,
  FollowUpAppointments_Object_text,
  FollowUpAppointments_placeholder_step_name,
  FollowUpAppointments_select_fields,
  FollowUpAppointments_button_save,
  FollowUpAppointments_button_cancel,
  FollowUpAppointments_duallist_available_fields,
  FollowUpAppointments_duallist_selected_fields,
  FollowUpAppointments_placeHolder_select_an_option,
  FollowUpAppointments_placeholder_search_fields,
  FollowUpAppointments_MobileWorkFlow_Info_text,
  FollowUpAppointments_MobileWorkFlow_info_help_url,
  FollowUpAppointments_delete_step_heading,
  FollowUpAppointments_delete_step_body,
  FollowUpAppointments_delete_cancel_button,
  FollowUpAppointments_delete_button_title,
  FollowUpAppointments_settings_duplicateScreenToastMessage,
  FollowUpAppointments_settings_deleteScreenToastMessage,
  FollowUpAppointments_settingPage_error_duplicate_screen,
  FollowUpAppointments_settingPage_error_delete_screen,
  FollowUpAppointments_settings_createScreenToastMessage,
  FollowUpAppointments_workflow_addStepFailureMessage,
  FollowUpAppointments_settingPage_save_message,
  FollowUpAppointments_settingPage_error_message,
};

export default customLabels;
