import FollowUpAppointments_your_appt_was_canceled_msg from '@salesforce/label/c.FollowUpAppointments_your_appt_was_canceled_msg';
import FollowUpAppointments_toastMessage_appointment_confirmed from '@salesforce/label/c.FollowUpAppointments_toastMessage_appointment_confirmed';
import FollowUpAppointments_toastMessage_appointment_schedule from '@salesforce/label/c.FollowUpAppointments_toastMessage_appointment_schedule';
import FollowUpAppointments_toastMessage_cancel_appointment_fail_message from '@salesforce/label/c.FollowUpAppointments_toastMessage_cancel_appointment_fail_message';
import FollowUpAppointments_toastMessage_confirm_appointment_fail_message from '@salesforce/label/c.FollowUpAppointments_toastMessage_confirm_appointment_fail_message';
import FollowUpAppointments_toastMessage_schedule_appointment_fail_message from '@salesforce/label/c.FollowUpAppointments_toastMessage_schedule_appointment_fail_message';
import FollowUpAppointments_same_appointment_selected_warning from '@salesforce/label/c.FollowUpAppointments_same_appointment_selected_warning';
import FollowUpAppointments_all_available_appointments from '@salesforce/label/c.FollowUpAppointments_all_available_appointments';
import FollowUpAppointments_recommended_appointments from '@salesforce/label/c.FollowUpAppointments_recommended_appointments';



const customLabels = {
    FollowUpAppointments_your_appt_was_canceled_msg,
    FollowUpAppointments_toastMessage_appointment_confirmed,
    FollowUpAppointments_toastMessage_appointment_schedule,
    FollowUpAppointments_toastMessage_cancel_appointment_fail_message,
    FollowUpAppointments_toastMessage_confirm_appointment_fail_message,
    FollowUpAppointments_toastMessage_schedule_appointment_fail_message,
    FollowUpAppointments_same_appointment_selected_warning,
    FollowUpAppointments_all_available_appointments,
    FollowUpAppointments_recommended_appointments,
}

export default customLabels;