import Reschedule_Appointment_cant_select_Mobile_Worker_excluded from "@salesforce/label/c.Reschedule_Appointment_cant_select_Mobile_Worker_excluded";
import Reschedule_Appointment_Mobile_Worker_radio_title from "@salesforce/label/c.Reschedule_Appointment_Mobile_Worker_radio_title";
import Reschedule_Appointment_Mobile_Worker_radio_assignToMe_lable from "@salesforce/label/c.Reschedule_Appointment_Mobile_Worker_radio_assignToMe_lable";
import Reschedule_Appointment_Mobile_Worker_radio_assignToAnyAvailable_lable from "@salesforce/label/c.Reschedule_Appointment_Mobile_Worker_radio_assignToAnyAvailable_lable";

const customLabels = {
  Reschedule_Appointment_cant_select_Mobile_Worker_excluded,
  Reschedule_Appointment_Mobile_Worker_radio_title,
  Reschedule_Appointment_Mobile_Worker_radio_assignToMe_lable,
  Reschedule_Appointment_Mobile_Worker_radio_assignToAnyAvailable_lable
};

export default customLabels;
