import MobileDashboard_basic_filter_field from "@salesforce/label/c.MobileDashboard_basic_filter_field";
import MobileDashboard_settings_select_placeholder from "@salesforce/label/c.MobileDashboard_settings_select_placeholder";
import MobileDashboard_basic_filter_operator from "@salesforce/label/c.MobileDashboard_basic_filter_operator";
import MobileDashboard_basic_filter_operator_equals from "@salesforce/label/c.MobileDashboard_basic_filter_operator_equals";
import MobileDashboard_basic_filter_operator_not_equal from "@salesforce/label/c.MobileDashboard_basic_filter_operator_not_equal";
import MobileDashboard_basic_filter_operator_less_than from "@salesforce/label/c.MobileDashboard_basic_filter_operator_less_than";
import MobileDashboard_basic_filter_operator_greater_than from "@salesforce/label/c.MobileDashboard_basic_filter_operator_greater_than";
import MobileDashboard_basic_filter_operator_less_or_equal from "@salesforce/label/c.MobileDashboard_basic_filter_operator_less_or_equal";
import MobileDashboard_basic_filter_operator_greater_or_equal from "@salesforce/label/c.MobileDashboard_basic_filter_operator_greater_or_equal";
import MobileDashboard_basic_filter_operator_contains from "@salesforce/label/c.MobileDashboard_basic_filter_operator_contains";
import MobileDashboard_basic_filter_date_operator from "@salesforce/label/c.MobileDashboard_basic_filter_date_operator";
import MobileDashboard_basic_filter_date_type_today from "@salesforce/label/c.MobileDashboard_basic_filter_date_type_today";
import MobileDashboard_basic_filter_date_type_last from "@salesforce/label/c.MobileDashboard_basic_filter_date_type_last";
import MobileDashboard_basic_filter_date_type_next from "@salesforce/label/c.MobileDashboard_basic_filter_date_type_next";
import MobileDashboard_basic_filter_date_type_on from "@salesforce/label/c.MobileDashboard_basic_filter_date_type_on";
import MobileDashboard_basic_filter_date_type_before from "@salesforce/label/c.MobileDashboard_basic_filter_date_type_before";
import MobileDashboard_basic_filter_date_type_after from "@salesforce/label/c.MobileDashboard_basic_filter_date_type_after";
import MobileDashboard_settings_card_display_operator_today from "@salesforce/label/c.MobileDashboard_settings_card_display_operator_today";
import MobileDashboard_settings_card_display_operator_next from "@salesforce/label/c.MobileDashboard_settings_card_display_operator_next";
import MobileDashboard_settings_card_display_operator_last from "@salesforce/label/c.MobileDashboard_settings_card_display_operator_last";
import MobileDashboard_settings_card_display_unit_days from "@salesforce/label/c.MobileDashboard_settings_card_display_unit_days";
import MobileDashboard_settings_card_display_unit_weeks from "@salesforce/label/c.MobileDashboard_settings_card_display_unit_weeks";
import MobileDashboard_settings_card_display_unit_months from "@salesforce/label/c.MobileDashboard_settings_card_display_unit_months";
import MobileDashboard_basic_filter_value from "@salesforce/label/c.MobileDashboard_basic_filter_value";
import MobileDashboard_basic_filter_unit from "@salesforce/label/c.MobileDashboard_basic_filter_unit";

const customLabels = {
  MobileDashboard_basic_filter_field,
  MobileDashboard_settings_select_placeholder,
  MobileDashboard_basic_filter_operator,
  MobileDashboard_basic_filter_operator_equals,
  MobileDashboard_basic_filter_operator_not_equal,
  MobileDashboard_basic_filter_operator_less_than,
  MobileDashboard_basic_filter_operator_greater_than,
  MobileDashboard_basic_filter_operator_less_or_equal,
  MobileDashboard_basic_filter_operator_greater_or_equal,
  MobileDashboard_basic_filter_operator_contains,
  MobileDashboard_basic_filter_date_operator,
  MobileDashboard_basic_filter_date_type_today,
  MobileDashboard_basic_filter_date_type_next,
  MobileDashboard_basic_filter_date_type_last,
  MobileDashboard_basic_filter_date_type_on,
  MobileDashboard_basic_filter_date_type_before,
  MobileDashboard_basic_filter_date_type_after,
  MobileDashboard_settings_card_display_operator_today,
  MobileDashboard_settings_card_display_operator_next,
  MobileDashboard_settings_card_display_operator_last,
  MobileDashboard_settings_card_display_unit_days,
  MobileDashboard_settings_card_display_unit_weeks,
  MobileDashboard_settings_card_display_unit_months,
  MobileDashboard_basic_filter_value,
  MobileDashboard_basic_filter_unit
};

export default customLabels;
