import MobileDashboard_card_modal_details_tab_name from '@salesforce/label/c.MobileDashboard_card_modal_details_tab_name';
import MobileDashboard_card_modal_details_name_field from '@salesforce/label/c.MobileDashboard_card_modal_details_name_field';
import MobileDashboard_card_object_field from '@salesforce/label/c.MobileDashboard_card_object_field';
import MobileDashboard_card_filter_title from '@salesforce/label/c.MobileDashboard_card_filter_title';
import MobileDashboard_card_modal_details_filter_logic_field from '@salesforce/label/c.MobileDashboard_card_modal_details_filter_logic_field';
import MobileDashboard_settings_select_placeholder from '@salesforce/label/c.MobileDashboard_settings_select_placeholder';
import MobileDashboard_card_modal_details_filter_logic_and from '@salesforce/label/c.MobileDashboard_card_modal_details_filter_logic_and';
import MobileDashboard_card_modal_details_filter_logic_or from '@salesforce/label/c.MobileDashboard_card_modal_details_filter_logic_or';
import MobileDashboard_card_modal_details_filter_logic_custom from '@salesforce/label/c.MobileDashboard_card_modal_details_filter_logic_custom';
import MobileDashboard_card_modal_details_custom_logic_field from '@salesforce/label/c.MobileDashboard_card_modal_details_custom_logic_field';
import MobileDashboard_card_modal_details_add_condition_button from '@salesforce/label/c.MobileDashboard_card_modal_details_add_condition_button';
import MobileDashboard_settings_save_button from '@salesforce/label/c.MobileDashboard_settings_save_button';
import MobileDashboard_settings_cancel_button from '@salesforce/label/c.MobileDashboard_settings_cancel_button';
import MobileDashboard_card_modal_design_tab_name from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_name';
import MobileDashboard_card_modal_design_tab_layout_title from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_layout_title';
import MobileDashboard_card_modal_design_tab_layout_side_title from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_layout_side_title';
import MobileDashboard_card_modal_design_tab_layout_side_description from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_layout_side_description';
import MobileDashboard_card_modal_design_tab_layout_stack_title from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_layout_stack_title';
import MobileDashboard_card_modal_design_tab_layout_stack_description from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_layout_stack_description';
import MobileDashboard_card_modal_design_tab_card_data_title from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_card_data_title';
import MobileDashboard_settings_delete_sub_filter_warning_title from '@salesforce/label/c.MobileDashboard_settings_delete_sub_filter_warning_title';
import MobileDashboard_settings_delete_sub_filter_warning_body from '@salesforce/label/c.MobileDashboard_settings_delete_sub_filter_warning_body';
import MobileDashboard_card_modal_design_tab_add_data_button from '@salesforce/label/c.MobileDashboard_card_modal_design_tab_add_data_button';
import MobileDashboard_card_modal_details_filter_field_infobubble from '@salesforce/label/c.MobileDashboard_card_modal_details_filter_field_infobubble';
import MobileDashboard_card_modal_details_remove_condition_button from '@salesforce/label/c.MobileDashboard_card_modal_details_remove_condition_button';
import MobileDashboard_card_modal_details_custom_logic_field_infobubble from '@salesforce/label/c.MobileDashboard_card_modal_details_custom_logic_field_infobubble';
import MobileDashboard_card_modal_details_and_between_logic from '@salesforce/label/c.MobileDashboard_card_modal_details_and_between_logic';
import MobileDashboard_card_modal_details_or_between_logic from '@salesforce/label/c.MobileDashboard_card_modal_details_or_between_logic';

const customLabels = {
  MobileDashboard_card_modal_details_tab_name,
  MobileDashboard_card_modal_details_name_field,
  MobileDashboard_card_object_field,
  MobileDashboard_card_modal_details_filter_field_infobubble,
  MobileDashboard_card_filter_title,
  MobileDashboard_card_modal_details_filter_logic_field,
  MobileDashboard_settings_select_placeholder,
  MobileDashboard_card_modal_details_filter_logic_and,
  MobileDashboard_card_modal_details_filter_logic_or,
  MobileDashboard_card_modal_details_filter_logic_custom,
  MobileDashboard_card_modal_details_custom_logic_field,
  MobileDashboard_card_modal_details_add_condition_button,
  MobileDashboard_settings_save_button,
  MobileDashboard_settings_cancel_button,
  MobileDashboard_card_modal_design_tab_name,
  MobileDashboard_card_modal_design_tab_layout_title,
  MobileDashboard_card_modal_design_tab_layout_side_title,
  MobileDashboard_card_modal_design_tab_layout_side_description,
  MobileDashboard_card_modal_design_tab_layout_stack_title,
  MobileDashboard_card_modal_design_tab_layout_stack_description,
  MobileDashboard_card_modal_design_tab_card_data_title,
  MobileDashboard_settings_delete_sub_filter_warning_title,
  MobileDashboard_settings_delete_sub_filter_warning_body,
  MobileDashboard_card_modal_design_tab_add_data_button,
  MobileDashboard_card_modal_details_remove_condition_button,
  MobileDashboard_card_modal_details_custom_logic_field_infobubble,
  MobileDashboard_card_modal_details_and_between_logic,
  MobileDashboard_card_modal_details_or_between_logic,
};

export default customLabels;
