import FollowUpAppointments_MonthName_January from "@salesforce/label/c.FollowUpAppointments_MonthName_January";
import FollowUpAppointments_MonthName_February from "@salesforce/label/c.FollowUpAppointments_MonthName_February";
import FollowUpAppointments_MonthName_March from "@salesforce/label/c.FollowUpAppointments_MonthName_March";
import FollowUpAppointments_MonthName_April from "@salesforce/label/c.FollowUpAppointments_MonthName_April";
import FollowUpAppointments_MonthName_May from "@salesforce/label/c.FollowUpAppointments_MonthName_May";
import FollowUpAppointments_MonthName_June from "@salesforce/label/c.FollowUpAppointments_MonthName_June";
import FollowUpAppointments_MonthName_July from "@salesforce/label/c.FollowUpAppointments_MonthName_July";
import FollowUpAppointments_MonthName_August from "@salesforce/label/c.FollowUpAppointments_MonthName_August";
import FollowUpAppointments_MonthName_September from "@salesforce/label/c.FollowUpAppointments_MonthName_September";
import FollowUpAppointments_MonthName_October from "@salesforce/label/c.FollowUpAppointments_MonthName_October";
import FollowUpAppointments_MonthName_November from "@salesforce/label/c.FollowUpAppointments_MonthName_November";
import FollowUpAppointments_MonthName_December from "@salesforce/label/c.FollowUpAppointments_MonthName_December";

import FollowUpAppointments_WeekDayLong_Monday from "@salesforce/label/c.FollowUpAppointments_WeekDayLong_Monday";
import FollowUpAppointments_WeekDayLong_Tuesday from "@salesforce/label/c.FollowUpAppointments_WeekDayLong_Tuesday";
import FollowUpAppointments_WeekDayLong_Wednesday from "@salesforce/label/c.FollowUpAppointments_WeekDayLong_Wednesday";
import FollowUpAppointments_WeekDayLong_Thursday from "@salesforce/label/c.FollowUpAppointments_WeekDayLong_Thursday";
import FollowUpAppointments_WeekDayLong_Friday from "@salesforce/label/c.FollowUpAppointments_WeekDayLong_Friday";
import FollowUpAppointments_WeekDayLong_Saturday from "@salesforce/label/c.FollowUpAppointments_WeekDayLong_Saturday";
import FollowUpAppointments_WeekDayLong_Sunday from "@salesforce/label/c.FollowUpAppointments_WeekDayLong_Sunday";

const customLabels = {
  FollowUpAppointments_MonthName_January,
  FollowUpAppointments_MonthName_February,
  FollowUpAppointments_MonthName_March,
  FollowUpAppointments_MonthName_April,
  FollowUpAppointments_MonthName_May,
  FollowUpAppointments_MonthName_June,
  FollowUpAppointments_MonthName_July,
  FollowUpAppointments_MonthName_August,
  FollowUpAppointments_MonthName_September,
  FollowUpAppointments_MonthName_October,
  FollowUpAppointments_MonthName_November,
  FollowUpAppointments_MonthName_December,

  FollowUpAppointments_WeekDayLong_Monday,
  FollowUpAppointments_WeekDayLong_Tuesday,
  FollowUpAppointments_WeekDayLong_Wednesday,
  FollowUpAppointments_WeekDayLong_Thursday,
  FollowUpAppointments_WeekDayLong_Friday,
  FollowUpAppointments_WeekDayLong_Saturday,
  FollowUpAppointments_WeekDayLong_Sunday
};

export default customLabels;
