import Appointment_ReBooking_new_appointment_msg from "@salesforce/label/c.Appointment_ReBooking_new_appointment_msg";
import Appointment_ReBooking_accept_new_appointment_button from "@salesforce/label/c.Appointment_ReBooking_accept_new_appointment_button";
import Appointment_ReBooking_bottom_sheet_success from "@salesforce/label/c.Appointment_ReBooking_bottom_sheet_success";
import Appointment_ReBooking_bottom_sheet_failure_title from "@salesforce/label/c.Appointment_ReBooking_bottom_sheet_failure_title";
import Appointment_ReBooking_bottom_sheet_failure_body from "@salesforce/label/c.Appointment_ReBooking_bottom_sheet_failure_body";
import Appointment_ReBooking_OK from "@salesforce/label/c.Appointment_ReBooking_OK";

const customLabels = {
  Appointment_ReBooking_new_appointment_msg,
  Appointment_ReBooking_accept_new_appointment_button,
  Appointment_ReBooking_bottom_sheet_success,
  Appointment_ReBooking_bottom_sheet_failure_title,
  Appointment_ReBooking_bottom_sheet_failure_body,
  Appointment_ReBooking_OK
};

export default customLabels;
