import FollowUpAppointments_preview_appointmentDateTime_title from "@salesforce/label/c.FollowUpAppointments_preview_appointmentDateTime_title";
import FollowUpAppointments_preview_appointmentDetails_title from "@salesforce/label/c.FollowUpAppointments_preview_appointmentDetails_title";
import FollowUpAppointments_preview_mobileWorker_title from "@salesforce/label/c.FollowUpAppointments_preview_mobileWorker_title";
import FollowUpAppointments_preview_step_not_editable from "@salesforce/label/c.FollowUpAppointments_preview_step_not_editable";
import FollowUpAppointments_preview_text from "@salesforce/label/c.FollowUpAppointments_preview_text";
import FollowUpAppointments_preview_step_help_text from "@salesforce/label/c.FollowUpAppointments_preview_step_help_text";

const customLabels = {
  FollowUpAppointments_preview_appointmentDateTime_title,
  FollowUpAppointments_preview_appointmentDetails_title,
  FollowUpAppointments_preview_mobileWorker_title,
  FollowUpAppointments_preview_step_not_editable,
  FollowUpAppointments_preview_text,
  FollowUpAppointments_preview_step_help_text
};

export default customLabels;
