import Reschedule_Appointment_your_appt_was_canceled_msg from "@salesforce/label/c.Reschedule_Appointment_your_appt_was_canceled_msg";
import Reschedule_Appointment_toastMessage_appointment_confirmed from "@salesforce/label/c.Reschedule_Appointment_toastMessage_appointment_confirmed";
import Reschedule_Appointment_toastMessage_appointment_reschedule from "@salesforce/label/c.Reschedule_Appointment_toastMessage_appointment_reschedule";
import Reschedule_Appointment_toastMessage_cancel_appointment_fail_message from "@salesforce/label/c.Reschedule_Appointment_toastMessage_cancel_appointment_fail_message";
import Reschedule_Appointment_toastMessage_confirm_appointment_fail_message from "@salesforce/label/c.Reschedule_Appointment_toastMessage_confirm_appointment_fail_message";
import Reschedule_Appointment_toastMessage_reschedule_appointment_fail_message from "@salesforce/label/c.Reschedule_Appointment_toastMessage_reschedule_appointment_fail_message";
import Reschedule_Appointment_same_appointment_selected_warning from "@salesforce/label/c.Reschedule_Appointment_same_appointment_selected_warning";
import Reschedule_Appointment_confirmation_failure_message from "@salesforce/label/c.Reschedule_Appointment_confirmation_failure_message";
import Reschedule_Appointment_all_available_appointments from "@salesforce/label/c.Reschedule_Appointment_all_available_appointments";
import Reschedule_Appointment_recommended_appointments from "@salesforce/label/c.Reschedule_Appointment_recommended_appointments";

const customLabels = {
  Reschedule_Appointment_your_appt_was_canceled_msg,
  Reschedule_Appointment_toastMessage_appointment_confirmed,
  Reschedule_Appointment_toastMessage_appointment_reschedule,
  Reschedule_Appointment_toastMessage_cancel_appointment_fail_message,
  Reschedule_Appointment_toastMessage_confirm_appointment_fail_message,
  Reschedule_Appointment_toastMessage_reschedule_appointment_fail_message,
  Reschedule_Appointment_same_appointment_selected_warning,
  Reschedule_Appointment_confirmation_failure_message,
  Reschedule_Appointment_all_available_appointments,
  Reschedule_Appointment_recommended_appointments
};

export default customLabels;
