import Appointment_ReBooking_your_appt_was_canceled_msg from '@salesforce/label/c.Appointment_ReBooking_your_appt_was_canceled_msg';
import Appointment_ReBooking_toastMessage_appointment_confirmed from '@salesforce/label/c.Appointment_ReBooking_toastMessage_appointment_confirmed';
import Appointment_ReBooking_toastMessage_appointment_reschedule from '@salesforce/label/c.Appointment_ReBooking_toastMessage_appointment_reschedule';
import Appointment_ReBooking_toastMessage_cancel_appointment_fail_message from '@salesforce/label/c.Appointment_ReBooking_toastMessage_cancel_appointment_fail_message';
import Appointment_ReBooking_toastMessage_confirm_appointment_fail_message from '@salesforce/label/c.Appointment_ReBooking_toastMessage_confirm_appointment_fail_message';
import Appointment_ReBooking_toastMessage_reschedule_appointment_fail_message from '@salesforce/label/c.Appointment_ReBooking_toastMessage_reschedule_appointment_fail_message';
import Appointment_ReBooking_same_appointment_selected_warning from '@salesforce/label/c.Appointment_ReBooking_same_appointment_selected_warning';
import AppointmentAssistance_confirmation_failure_message from '@salesforce/label/c.AppointmentAssistance_confirmation_failure_message';
import Appointment_ReBooking_new_appointment_msg from '@salesforce/label/c.Appointment_ReBooking_new_appointment_msg';
import Appointment_ReBooking_accept_new_appointment_button from '@salesforce/label/c.Appointment_ReBooking_accept_new_appointment_button';
import Appointment_ReBooking_assigned_to_you from '@salesforce/label/c.Appointment_ReBooking_assigned_to_you';
import Appointment_ReBooking_assigned_to_any_available_worker from '@salesforce/label/c.Appointment_ReBooking_assigned_to_any_available_worker';
import Appointment_ReBooking_all_available_appointments from '@salesforce/label/c.Appointment_ReBooking_all_available_appointments';
import Appointment_ReBooking_recommended_appointments from '@salesforce/label/c.Appointment_ReBooking_recommended_appointments';

const customLabels = {
    Appointment_ReBooking_your_appt_was_canceled_msg,
    Appointment_ReBooking_toastMessage_appointment_confirmed,
    Appointment_ReBooking_toastMessage_appointment_reschedule,
    Appointment_ReBooking_toastMessage_cancel_appointment_fail_message,
    Appointment_ReBooking_toastMessage_confirm_appointment_fail_message,
    Appointment_ReBooking_toastMessage_reschedule_appointment_fail_message,
    Appointment_ReBooking_same_appointment_selected_warning,
    AppointmentAssistance_confirmation_failure_message,
    Appointment_ReBooking_new_appointment_msg,
    Appointment_ReBooking_accept_new_appointment_button,
    Appointment_ReBooking_assigned_to_you,
    Appointment_ReBooking_assigned_to_any_available_worker,
    Appointment_ReBooking_all_available_appointments,
    Appointment_ReBooking_recommended_appointments
}

export default customLabels;