import Reschedule_Appointment_page_title from "@salesforce/label/c.Reschedule_Appointment_page_title";
import Reschedule_Appointment_select_new_date_to_reschedule from "@salesforce/label/c.Reschedule_Appointment_select_new_date_to_reschedule";
import Reschedule_Appointment_select_an_available_appointment_time from "@salesforce/label/c.Reschedule_Appointment_select_an_available_appointment_time";
import Reschedule_Appointment_current_appointment_msg from "@salesforce/label/c.Reschedule_Appointment_current_appointment_msg";
import Reschedule_Appointment_accept_new_appointment_button from "@salesforce/label/c.Reschedule_Appointment_accept_new_appointment_button";
import Reschedule_Appointment_next_button_title from "@salesforce/label/c.Reschedule_Appointment_next_button_title";
import Reschedule_Appointment_new_appointment_msg from "@salesforce/label/c.Reschedule_Appointment_new_appointment_msg";
import Reschedule_Appointment_same_appointment_selected_warning from "@salesforce/label/c.Reschedule_Appointment_same_appointment_selected_warning";
import Reschedule_Appointment_confirmation_service_requested from "@salesforce/label/c.Reschedule_Appointment_confirmation_service_requested";
import Reschedule_Appointment_selected_appointment_msg from "@salesforce/label/c.Reschedule_Appointment_selected_appointment_msg";
import Reschedule_Appointment_toastMessage_appointment_reschedule from "@salesforce/label/c.Reschedule_Appointment_toastMessage_appointment_reschedule";
import Reschedule_Appointment_confirmation_failure_message from "@salesforce/label/c.Reschedule_Appointment_confirmation_failure_message";
import Reschedule_Appointment_toastMessage_reschedule_appointment_fail_message from "@salesforce/label/c.Reschedule_Appointment_toastMessage_reschedule_appointment_fail_message";
import Reschedule_Appointment_assigned_to_you from "@salesforce/label/c.Reschedule_Appointment_assigned_to_you";
import Reschedule_Appointment_assigned_to_any_available_worker from "@salesforce/label/c.Reschedule_Appointment_assigned_to_any_available_worker";

const customLabels = {
  Reschedule_Appointment_select_new_date_to_reschedule,
  Reschedule_Appointment_select_an_available_appointment_time,
  Reschedule_Appointment_current_appointment_msg,
  Reschedule_Appointment_accept_new_appointment_button,
  Reschedule_Appointment_next_button_title,
  Reschedule_Appointment_new_appointment_msg,
  Reschedule_Appointment_same_appointment_selected_warning,
  Reschedule_Appointment_confirmation_service_requested,
  Reschedule_Appointment_selected_appointment_msg,
  Reschedule_Appointment_page_title,
  Reschedule_Appointment_toastMessage_appointment_reschedule,
  Reschedule_Appointment_confirmation_failure_message,
  Reschedule_Appointment_toastMessage_reschedule_appointment_fail_message,
  Reschedule_Appointment_assigned_to_you,
  Reschedule_Appointment_assigned_to_any_available_worker
};

export default customLabels;
