import Reschedule_Appointment_no_available_appointments_msg from "@salesforce/label/c.Reschedule_Appointment_no_available_appointments_msg";
import Reschedule_Appointment_MonthName_January from "@salesforce/label/c.Reschedule_Appointment_MonthName_January";
import Reschedule_Appointment_MonthName_February from "@salesforce/label/c.Reschedule_Appointment_MonthName_February";
import Reschedule_Appointment_MonthName_March from "@salesforce/label/c.Reschedule_Appointment_MonthName_March";
import Reschedule_Appointment_MonthName_April from "@salesforce/label/c.Reschedule_Appointment_MonthName_April";
import Reschedule_Appointment_MonthName_May from "@salesforce/label/c.Reschedule_Appointment_MonthName_May";
import Reschedule_Appointment_MonthName_June from "@salesforce/label/c.Reschedule_Appointment_MonthName_June";
import Reschedule_Appointment_MonthName_July from "@salesforce/label/c.Reschedule_Appointment_MonthName_July";
import Reschedule_Appointment_MonthName_August from "@salesforce/label/c.Reschedule_Appointment_MonthName_August";
import Reschedule_Appointment_MonthName_September from "@salesforce/label/c.Reschedule_Appointment_MonthName_September";
import Reschedule_Appointment_MonthName_October from "@salesforce/label/c.Reschedule_Appointment_MonthName_October";
import Reschedule_Appointment_MonthName_November from "@salesforce/label/c.Reschedule_Appointment_MonthName_November";
import Reschedule_Appointment_MonthName_December from "@salesforce/label/c.Reschedule_Appointment_MonthName_December";

import Reschedule_Appointment_WeekDayLong_Monday from "@salesforce/label/c.Reschedule_Appointment_WeekDayLong_Monday";
import Reschedule_Appointment_WeekDayLong_Tuesday from "@salesforce/label/c.Reschedule_Appointment_WeekDayLong_Tuesday";
import Reschedule_Appointment_WeekDayLong_Wednesday from "@salesforce/label/c.Reschedule_Appointment_WeekDayLong_Wednesday";
import Reschedule_Appointment_WeekDayLong_Thursday from "@salesforce/label/c.Reschedule_Appointment_WeekDayLong_Thursday";
import Reschedule_Appointment_WeekDayLong_Friday from "@salesforce/label/c.Reschedule_Appointment_WeekDayLong_Friday";
import Reschedule_Appointment_WeekDayLong_Saturday from "@salesforce/label/c.Reschedule_Appointment_WeekDayLong_Saturday";
import Reschedule_Appointment_WeekDayLong_Sunday from "@salesforce/label/c.Reschedule_Appointment_WeekDayLong_Sunday";
import Reschedule_Appointment_today_text from "@salesforce/label/c.Reschedule_Appointment_today_text";
import Reschedule_Appointment_all_available_appointments from "@salesforce/label/c.Reschedule_Appointment_all_available_appointments";
import Reschedule_Appointment_recommended_appointments from "@salesforce/label/c.Reschedule_Appointment_recommended_appointments";
import Reschedule_Appointment_empty_state_select_any_available_worker from "@salesforce/label/c.Reschedule_Appointment_empty_state_select_any_available_worker";
import Reschedule_Appointment_empty_state_change_the_dates from "@salesforce/label/c.Reschedule_Appointment_empty_state_change_the_dates";

const customLabels = {
  Reschedule_Appointment_no_available_appointments_msg,
  Reschedule_Appointment_today_text,

  Reschedule_Appointment_MonthName_January,
  Reschedule_Appointment_MonthName_February,
  Reschedule_Appointment_MonthName_March,
  Reschedule_Appointment_MonthName_April,
  Reschedule_Appointment_MonthName_May,
  Reschedule_Appointment_MonthName_June,
  Reschedule_Appointment_MonthName_July,
  Reschedule_Appointment_MonthName_August,
  Reschedule_Appointment_MonthName_September,
  Reschedule_Appointment_MonthName_October,
  Reschedule_Appointment_MonthName_November,
  Reschedule_Appointment_MonthName_December,

  Reschedule_Appointment_WeekDayLong_Monday,
  Reschedule_Appointment_WeekDayLong_Tuesday,
  Reschedule_Appointment_WeekDayLong_Wednesday,
  Reschedule_Appointment_WeekDayLong_Thursday,
  Reschedule_Appointment_WeekDayLong_Friday,
  Reschedule_Appointment_WeekDayLong_Saturday,
  Reschedule_Appointment_WeekDayLong_Sunday,
  Reschedule_Appointment_all_available_appointments,
  Reschedule_Appointment_recommended_appointments,
  Reschedule_Appointment_empty_state_select_any_available_worker,
  Reschedule_Appointment_empty_state_change_the_dates
};

export default customLabels;
