import FollowUpAppointments_cant_select_Mobile_Worker_excluded from '@salesforce/label/c.FollowUpAppointments_cant_select_Mobile_Worker_excluded';
import FollowUpAppointments_Mobile_Worker_radio_title from '@salesforce/label/c.FollowUpAppointments_Mobile_Worker_radio_title';
import FollowUpAppointments_Mobile_Worker_radio_assignToMe_lable from '@salesforce/label/c.FollowUpAppointments_Mobile_Worker_radio_assignToMe_lable';
import FollowUpAppointments_Mobile_Worker_radio_assignToAnyAvailable_lable from '@salesforce/label/c.FollowUpAppointments_Mobile_Worker_radio_assignToAnyAvailable_lable';

const customLabels = {
  FollowUpAppointments_cant_select_Mobile_Worker_excluded,
  FollowUpAppointments_Mobile_Worker_radio_title,
  FollowUpAppointments_Mobile_Worker_radio_assignToMe_lable,
  FollowUpAppointments_Mobile_Worker_radio_assignToAnyAvailable_lable,
};

export default customLabels;
